### ISSUE TITLE
Why does indent/xml.vim remove !^F from indentkeys?

### ISSUE THREAD

**Issue by kiryph** [chrisbra/vim-xml-ftplugin#1]
The default value for the vim setting `'indentkeys'`/`'indk'` is `"0{,0},:,0#,!^F,o,O,e"`.

When `!^F` is removed from `'indk'`, the plugin [vim-ragtag](https://github.com/tpope/vim-ragtag) ('ghetto' HTML/XML mappings) inserts spurious `^F` into the file when e.g. pressing `<C-x>/`.

Actually, vim-ragtag tries to ensure that `!^F` is one of the indentkeys in 

https://github.com/tpope/vim-ragtag/blob/master/plugin/ragtag.vim#L236

However, this will be overwritten by filetype specific scripts which are loaded at a later point in time, i.e. by `$VIMRUNTIME/indent/xml.vim`.

This has been encountered by other before:

- https://github.com/tpope/vim-ragtag/issues/32
- https://github.com/othree/html5.vim/issues/37
- https://github.com/tpope/vim-ragtag/issues/48

The proposed solution by tpope in https://github.com/tpope/vim-ragtag/issues/48 does not work for me.

I will create locally the file `~/.vim/after/indent/xml.vim` with the line `setlocal indentkeys+=!^F` to avoid this problem. But maybe this could be resolved in upstream as well.

**Comment by chrisbra** [comment]
thanks. I do not know, why this was there originally. I added the `!^F` back and pushed the change. I'll send the updated indent script to Bram for inclusion with Vim.

**Comment by kiryph** [comment]
Thanks.

I checked the history of the file `runtime/indent/xml.vim` in upstream: the line in question predates the git commit history, i.e. before 7.0001.

It looks like `!^F` had been removed since the file had been added to vimruntime:
I have downloaded from `ftp://ftp.vim.org/pub/vim/unix` old vim releases. v5.8 does not contain the file but v6.0. At this point the documentation of `'indentkeys'` reads

`vim60/runtime/docs/options.txt`
```
						*'indentkeys'* *'indk'*
'indentkeys' 'indk'	string	(default "0{,0},:,0#,!^F,o,O,e")
			local to buffer
			{not in Vi}
			{not available when compiled without the |+cindent|
			feature}
	A list of keys that, when typed in Insert mode, cause reindenting of
	the current line.  Only happens if 'indentexpr' isn't empty.
	The format is identical to 'cinkeys', see |indentkeys-format|.
	See |C-indenting| and |indent-expression|.
```

and the file `vim60/runtime/indent/xml.vim` contains already the line without `!^F`

`setlocal indentkeys=o,O,*<Return>,<>>,<<>,/,<bs>,{,}`

The only change done to the line was removing `<bs>`.

Anyhow, if it is a problem for someone else, he/she will hopefully report it.

**Comment by chrisbra** [comment]
yeah I know. We would have to ask the previous indent file maintainer if there was a reason for that. Anyhow, I have send the change to Bram, he will included with the next runtime file update.
