### ISSUE TITLE
text inside tag has extra indentation

### ISSUE THREAD

**Issue by poscogrubb** [chrisbra/vim-xml-ftplugin#10]
<hello>
      <blah>
          world
      </blah>
    </hello>

I get the above indentation, where the line "world" is indented by 2 extra spaces. The 'w' of 'world' should line up with the 'l' in the opening tag 'blah'.

A colleague says that it's a bug in ptag_pattern of indent/xml.vim:111, that `line('.')` should be `a:lnum` instead. I don't know vimscript, so I cannot evaluate the correctness of that statement.

**Comment by chrisbra** [comment]
That was done on purpose, because I like it much better this way. However, for me the indentation works as you expect, e.g. there is no extra indentation for non-xml tags.

> A colleague says that it's a bug in ptag_pattern of indent/xml.vim:111, that line('.') should be a:lnum instead. I don't know vimscript, so I cannot evaluate the correctness of that statement.

That looks like your colleague is correct. I changed it.
