### ISSUE TITLE
`use_syntax_check` parameter doesn't work when it's 0

### ISSUE THREAD

**Issue by leafOfTree** [chrisbra/vim-xml-ftplugin#13]
Hi,
`XmlIndentGet(lnum, 0)` seems not to work, as it just adds indentation. After I checked `indent/xml.vim`, I found that if `a:use_syntax_check` is 0, `syn_name_*` will always be empty. So maybe should it be like this?

```diff
    if a:use_syntax_check
        let check_lnum = <SID>XmlIndentSynCheck(ptag)
        let check_alnum = <SID>XmlIndentSynCheck(a:lnum)
        if check_lnum == 0 || check_alnum == 0
            return indent(a:lnum)
        endif
-       let syn_name_end   = synIDattr(synID(a:lnum, strlen(curline) - 1, 1), 'name')
-       let syn_name_start = synIDattr(synID(a:lnum, match(curline, '\S') + 1, 1), 'name')
    endif

+   let syn_name_end   = synIDattr(synID(a:lnum, strlen(curline) - 1, 1), 'name')
+   let syn_name_start = synIDattr(synID(a:lnum, match(curline, '\S') + 1, 1), 'name')
    if syn_name_end =~ 'Comment' && syn_name_start =~ 'Comment'
        return <SID>XmlIndentComment(a:lnum)
    elseif empty(syn_name_start) && empty(syn_name_end)
        " non-xml tag content: use indent from 'autoindent'
        return pind + shiftwidth()
    endif
```
Thanks.

**Comment by chrisbra** [comment]
No that is wrong. The intention is that `syn_name_end` and `syn_name_start` is only determined, if the `use_syntax_check` parameter is 1 (which by default it is for xml filetypes. The reason is, that other filetypes like `docbk.vim` import this indent script (however for those it doesn't make sense to use XML syntax names.

**Comment by leafOfTree** [comment]
Thank you for the explanation, but when the `use_syntax_check` is 0, both `syn_name_end` and `syn_name_start` are empty, so `XmlIndentGet(lnum, 0)` which `dockbk.vim` and others invoke will always return `pind + shiftwidth()`, which leads to something like
```
<template>
    <div></div>
        </template>
```
I haven't used `dockbk.vim`, is this behaviour expected?

**Comment by chrisbra** [comment]
I don't know. The logic was like this when I took over maintenance and I haven't heard complaints yet.
