### ISSUE TITLE
Maintain xml syntax here?

### ISSUE THREAD

**Issue by dimbleby** [chrisbra/vim-xml-ftplugin#15]
Is there a reason that this repository does not include the xml syntax?

I know of at least one bug that people have been unable to get into the vim runtime on account of maintainer inactivity (vim/vim#884, rediscovered in gruvbox-community/gruvbox#104).

The maintainer of the xml syntax file is listed as Johannes Zellner - who is the same inactive maintainer that, I suppose, caused this repository to be created for the indent etc.

Wouldn't it make sense to include the syntax file here?

If yes, I expect I could manage a pull request adding the fix mentioned above.

**Comment by chrisbra** [comment]
I did not remember #884. Well, I guess I can maintain the syntax file here. I don't really mind. However I don't expect to be able to work on any issues, so would need the help of the community.

**Comment by chrisbra** [comment]
Okay, I have included the xml syntax file from Vim here as well. Please feel free to create a PR fixing any issues you notice. Thanks!

**Comment by dimbleby** [comment]
Great, thanks - I'll see if I can recover the fix that people have been trying to make at #884 and get that up here.
