### ISSUE TITLE
textwidth ignored when reformatting

### ISSUE THREAD

**Issue by jadahl** [chrisbra/vim-xml-ftplugin#18]
If I have a tag with a very long line, e.g.

```xml
<tag>
  Very long text very long text very long text very long text very long text very long text.
</tag>
```

with the `shiftwidth` to 2, and `textwidth` set to 80, then try to reformat the line so long line is broken up, using `gql` when on the long line, it does't break it up.

If I have two very long lines, e.g.

```xml
<tag>
  Very long text very long text very long text very long text very long text very long text.
  Very long text very long text very long text very long text very long text very long text.
</tag>
```

then go to the first long line, press `gqj`, the lines are concatinated instead of reformatted correctly.

```xml
<tag>
  Very long text very long text very long text very long text very long text very long text.   Very long text very long text very long text very long text very long text very long text.
</tag>
```

What I would have expected, given the textwidth is set to 80, is

```xml
<tag>
  Very long text very long text very long text very long text very long text 
  very long text. Very long text very long text very long text very long text 
  very long text very long text.
</tag>
```

I'm currently using VIM 8.1 1-1991. I have tried the bundled vim-xml-runtime, and the one in this repository, and it makse no difference.

**Comment by chrisbra** [comment]
so this is about https://github.com/chrisbra/vim-xml-runtime/blob/master/autoload/xmlformat.vim, right?

**Comment by jadahl** [comment]
Yes, I assume so. `formatexpr` points to the function in there in my xml buffers as far as I know.

**Comment by chrisbra** [comment]
yes okay, I'll have a look soon.

**Comment by jadahl** [comment]
Thanks! I just tested it, and it works well if there is a single paragraph in a text element. When there is more it behaves strangely.

Here are some examples that currently don't work (with `textwidth=80`):

Original:
```xml
<tag>
  A long line that will be split up into multiple lines once it's reformatted with a text width.

  A second long line that also will be split up into multiple lines once it's reformatted with a text width.
</tag>
```
Expected:

```xml
<tag>
  A long line that will be split up into multiple lines once it's reformatted
  with a text width.

  A second long line that also will be split up into multiple lines once it's
  reformatted with a text width.
</tag>
```

If I reformat each line individually (`gql` on each original lines, after the first line the empty line in between is gone, after reformatting the second line it's indented one time too many):

```xml
<tag>
  A long line that will be split up into multiple lines once it's reformatted
  with a text width.
    A second long line that also will be split up into multiple lines once
    it's reformatted with a text width.
</tag>
```

If I reformat everything in one go (`<Shift>v` -> select everything inside the `<tag/>` -> `gq`)

```xml
<tag>
  A long line that will be split up into multiple lines once it's reformatted
  with a text width.    A second long line that also will be split up into
  multiple lines once it's reformatted with a text width.
</tag>
```

want me to open a new issue for these cases?

**Comment by chrisbra** [comment]
no, I'll re-open. I also noticed that behaviour that several lines will be joined to one, before they are reformated. That's the way, this script iterates over the content of the buffer. This shows, it has some drawbacks.

I did not notice the extra indenting. I'll have another look.

**Comment by chrisbra** [comment]
check if this works now better.

**Comment by jadahl** [comment]
It works a lot better now!

I can only find one issue left. With `textwidth=80`

```xml
<tag>
  A long line that will be split up into multiple lines once it's reformatted
  with a text width.

  A second long line that also will be split up into multiple lines once it's
  reformatted with a text width.
</tag>
```

results in

```xml
<tag>
  A long line that will be split up into multiple lines once it's reformatted
  with a text width.

  A second long line that also will be split up into multiple lines once
  it's
  reformatted with a text width.
</tag>
```

when being reformatted. Note that the original text at its longest was only 77 characters wide to begin with.

**Comment by chrisbra** [comment]
Yes, but it only wraps on whitespace, so it checks 10 characters before the textwidth limit whether there is whitespace to wrap on. But I would say that is okay. I have a look at the last issue and see if this can be fixed easily.

**Comment by jadahl** [comment]
Just tested, and works even better now :) Thanks a lot!

Thought of another scenario where it can be improved to be on-par with how formatting works in e.g. C comments etc: join shorter lines in a paragraph. E.g.

```xml
<tag>
  A paragraph
  split
  up in multiple short
  lines.
</tag>
```

should, when reformatted, result in

```xml
<tag>
  A paragraph split up in multiple short lines.
</tag>
```

similar to how

```c
/*
 * A paragraph
 * split
 * up in multiple short
 * lines.
 */
```

will be reformatted to

```c
/*
 * A paragraph split up in multiple short lines.
 */
```

**Comment by chrisbra** [comment]
Yeah, it works linewise. I will have a look.

**Comment by chrisbra** [comment]
I just changed it yesterday from joining the whole content into a long string to one single string and process from there. However than we lose empty new lines again...

**Comment by jadahl** [comment]
Maybe change it to work paragraph wise? I.e. detect the empty line (i.e. two or more line breaks with just whitespace or nothing in between).
