### ISSUE TITLE
Refine spell-checked regions of XML files

### ISSUE THREAD

**Issue by jamessan** [chrisbra/vim-xml-ftplugin#19]
Some time ago, a [Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=531293) requested adjusting the way spell checking is configured for XML files.

> For XML files (ft=xml or ft=docbk) Vim currently:
> 
> - Spell checks attribute values, which is not very helpful, as they 
typically contain numbers, URIs or some kind of identifiers.
> 
> - Does not spell check contents of text nodes, which would be desired, 
as they typically contain, well, text.

Could the spell checked regions be reviewed to see if there are adjustments, like the above, that should be made?

**Comment by chrisbra** [comment]
> Spell checks attribute values, which is not very helpful, as they
typically contain numbers, URIs or some kind of identifiers.

I don't agree, I have seen to many attribute values where text has been used and it should therefore be spell checked. 

> Does not spell check contents of text nodes, which would be desired,
as they typically contain, well, text.

Yeah, there is no general syntax element for nodes values, so let's just enable spell checking for the top-level elements (for which no syntax rules have been defined).
