### ISSUE TITLE
Bad indentation for docbk files

### ISSUE THREAD

**Issue by tbazant** [chrisbra/vim-xml-ftplugin#20]
Since the switch to openSUSE tubmbleweed and vim 8.1, i experience bad indentation when filetype is set/autoset to 'docbk'. It creates a staircase effect, such as the following

> <variablelist>
     <varlistentry>
      <term></term>
       <listitem>
        <para>
         </para>
          </listitem>
           </varlistentry>
            </variablelist>

I looked into `indent/docbk.vim` file, but it only seems to include `indent/xml.vim`. If i set filetype to 'xml' manually, the indentation behavior becomes correct.

**Comment by chrisbra** [comment]
hm, how do you reproduce this?

**Comment by chrisbra** [comment]
looks a bit like #14

**Comment by tbazant** [comment]
Reproduce:

* Download a docbook file such as https://github.com/SUSE/doc-ses/blob/master/xml/admin_about.xml
* open it in the latest vi
* check that the filetype is `docbk` with `:set ft`
* make sure `filetype plugin indent on` is in your .vimrc
* make sure `set smartindent` is in your .vimrc
* then try writing some xml, such as <tip><ENTER><para>some text</para></tip>

now when you set the filetype to pure xml with `:set ft=xml`, everything works fine

**Comment by chrisbra** [comment]
okay, thanks I see the problem now. Should be fixed
