### ISSUE TITLE
Autoclosing tag and autoindent

### ISSUE THREAD

**Issue by maieul** [chrisbra/vim-xml-ftplugin#25]
(previously posted on https://vi.stackexchange.com/q/25548/29788)

Here my vimrc

    filetype plugin indent on
    set autoindent 
    set tabstop=2 
    set shiftwidth=2 
    set softtabstop=2 

And that all.

Let suppose I start a new xml file.

WHen a use normal tag, autoindent work well

    <div>
      <p> 
         Some text
      </p>
    </div>

But if I insert autoclosing tags, autoindnet don't recognize the autoclosing feature,and I get something like this.

    <div>
      <p> 
         Some text<lb />
            Some text<lb />
                 Some text<lb />
      </p>
    </div>

I use vim 8.1.2269. I tried with nvim 0.4.3 > same problem. WHat is strange is that in the past (before my new fresh installation of Ubuntu), I didn't get any problem...

**Comment by chrisbra** [comment]
what version did you use previously?

**Comment by maieul** [comment]
don't know. But it was the version distributed with Ubuntu 18.04 TLS. Now, I am on ubuntu 20.04.

i tried on my serveur, and v 7 of vim worked.

**Comment by chrisbra** [comment]
okay, I have that version available. Can you check if this patch fixes it for you:
```patch
diff --git a/indent/xml.vim b/indent/xml.vim
index 867f0bd..a59b3fd 100644
--- a/indent/xml.vim
+++ b/indent/xml.vim
@@ -81,7 +81,7 @@ endfun

 " [-- return the sum of indents of a:lnum --]
 fun! <SID>XmlIndentSum(line, style, add)
-    if <SID>IsXMLContinuation(a:line) && a:style == 0
+    if <SID>IsXMLContinuation(a:line) && a:style == 0 && !<SID>IsXMLEmptyTag(a:line)
         " no complete tag, add one additional indent level
         " but only for the current line
         return a:add + shiftwidth()
@@ -156,6 +156,11 @@ func! <SID>IsXMLContinuation(line)
     return a:line !~ '^\s*<' && &ft is# 'xml'
 endfunc

+func! <SID>IsXMLEmptyTag(line)
+    " Checks, whether line ends with an empty closing tag eg: <lb/>
+    return a:line =~? '/>\?\s*$' && &ft is# 'xml'
+endfunc
+
 func! <SID>HasNoTagEnd(line)
     " Checks whether or not the line matches '>' (so finishes a tag)
     return a:line !~ '>\s*$'

```
I have to have a closer look later.

**Comment by maieul** [comment]
Thank you.
where should I put the file for the test? I tried this 
1. Copy `/usr/share/vim/vim81/indent/xml.vim` in `~/.vim/ftplugin/indent`
2. Patch it
3. Running vim

I have the same issue, but maybe I dont something wrong (I am not a vim neerd)

**Comment by chrisbra** [comment]
no worries, I'll check it later. I must verify it doesn't brake any tests.

**Comment by maieul** [comment]
oki, so my test was method was good?

**Comment by chrisbra** [comment]
okay, should be fixed now. Clone this repo into your pack path, and it should work with your xml files.
Will send an update for inclusion with Vim soon to Bram.

**Comment by maieul** [comment]
yes it works, thank you very much !
