### ISSUE TITLE
Indent error for comment

### ISSUE THREAD

**Issue by ShwetaSoftwares** [chrisbra/vim-xml-ftplugin#28]
Write a XML file containing these tags:

```xml
<MASTER TYPE="LEDGER">
  <!-- comment1 -->
  <PARENT FORMULA="someformula"/>
  <!-- comment2 -->
  <SOMETAG>Yes</SOMETAG>
  <!-- comment3 -->
  <ANOTHERTAG>Yes</ANOTHERTAG>
  <!-- comment4 -->
  <AFFECTSSTOCK FORMULA="someformula"/>
  <!-- comment5 -->
</MASTER>
```

Next, when I reformat it (gg=G), the XML is changed to:

```xml
<MASTER TYPE="LEDGER">
  <!-- comment1 -->
  <PARENT FORMULA="someformula"/>
  <!-- comment2 -->
  <SOMETAG>Yes</SOMETAG>
    <!-- comment3 -->
  <ANOTHERTAG>Yes</ANOTHERTAG>
    <!-- comment4 -->
  <AFFECTSSTOCK FORMULA="someformula"/>
  <!-- comment5 -->
</MASTER>
```

As you can see the comments viz **comment3** and **comment4** have wrong indentation. Both these comments appear after elements  (viz SOMETAG and ANOTHERTAG) which have text-nodes / values. The expected result is same as before reformat.

**Comment by chrisbra** [comment]
ah, I did not see this message. Should be fixed now.
