### ISSUE TITLE
indent error

### ISSUE THREAD

**Issue by zcodes** [chrisbra/vim-xml-ftplugin#4]
In Function XmlIndentGet, origin code is 
```viml
let plnum = prevnonblank(a:lnum - 1)
```
then the indent is calced based on the previous line's indent,

current code is 
```viml
let ptag = search('.\{-}<[/:A-Z_a-z]', 'bnw')
```

when edit a line like this with a xml tag
```xml
<message ${cursor}
```
the current line is matched, the caclulation will based on the current line's indent, then it will always increase a shiftwidth indent.

**Comment by andrewacashner** [comment]
Yes, typing `=` in command mode now uniformly increases indentation of opening tags and decreases indentation of close tags regardless of context.
Also, typing `/` in any context now increases the indentation!

**Comment by chrisbra** [comment]
So is this an error or not? Not sure I understand.

**Comment by zcodes** [comment]
yes, it's an error

**Comment by zcodes** [comment]
you can open an xml file, and put contents below:

```xml
<user>
   <name>
</user>
```

in line 2 (after the tag `<name>`, you insert `>` or use `==` to indent current line, you will see what happed !

**Comment by amkarthik** [comment]
Yes. Its an issue.

**Comment by erquhart** [comment]
Ran into this after updating from Vim 8.0 to 8.1, all of the React JSX syntax plugins rely on it. @chrisbra let me know if I can help test anything.

**Comment by chrisbra** [comment]
okay, i think I have fixed it. Please verify.

**Comment by mismosmi** [comment]
works, thanks!

**Comment by amkarthik** [comment]
Great.

**Comment by chrisbra** [comment]
Thanks. Will send an update to Bram for inclusion with Vim.

**Comment by zcodes** [comment]
works, thanks !
