### ISSUE TITLE
Dynamic indentation breaks block editing

### ISSUE THREAD

**Issue by SammysHP** [chrisbra/vim-xml-ftplugin#8]
Not sure if it is worth or possible to fix this, but there is an annoying behavior of the indentation function that breaks block editing (<kbd>Ctrl</kbd>+<kbd>v</kbd> <kbd>j</kbd> <kbd>j</kbd> <kbd>j</kbd> <kbd>I</kbd>). If you start writing something that changes indentation, the indentation will update and after pressing <kbd>Esc</kbd> other edited lines are broken. `:set paste` will help, but is a bit inconvenient to use all the time.

**Comment by chrisbra** [comment]
I don't think block-editing is currently possible to detect. So I cannot make any changes here.
